services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  frontend:
    build:
      context: .
      dockerfile: Lab1_Frontend/Dockerfile
    environment:
      BACKEND_URL: /
      API_PROXY_PASS: http://webapi:8080
    ports:
      - "8085:80"
    depends_on:
      - webapi
